### ISSUE TITLE
How to run the benchmark?

### ISSUE THREAD

**Issue by aclueless** [schell/todo-mvc-bench#34]
I saw `/scripts/build.sh`, I ran it.
Now I have a new folder `/release`. I ran `basic-http-server` in it and open the page but the browser say `window.wasm_bindgen is not a function`.

How should I run it?

**Comment by schell** [comment]
I've run into that as well. Let me do a little digging and I'll get back to you.

**Comment by schell** [comment]
I just pushed a change that should fix your problem. I also added a building and running section to the README.

**Comment by aclueless** [comment]
Thanks!
