### ISSUE TITLE
A table with frameworks as rows instead of cards?

### ISSUE THREAD

**Issue by aclueless** [schell/todo-mvc-bench#37]
As you want to benchmark many frameworks from many different languages, I expect that the number of frameworks is very high. Is it a better to have them list as rows of a table?

|Frameworks|Version|Approach|Language|Size(*)|Score(ms)|Notes|
|---|---|---|---|---|---|---|
|mogwai|0.2|?|Rust|?| ? ||
|react|?|vDOM|JS|?|?|error message|

(*) size of all files need to deliver to browser (in kB)

**Comment by schell** [comment]
Yeah this makes sense.
